version: "3"
services:
  meilisearch:
    image: getmeili/meilisearch:v0.30
    ports:
      - "7700:7700"
    volumes:
      - "./meili_data:/meili_data"
      - "./meili_data/data.ms:/home/meili/data.ms"
  node-app:
    build: .
    links:
      - meilisearch
    ports:
      - "8080:8080"
    depends_on:
      - meilisearch
